#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

# solves JAVA reparenting issues (windows show up blank).  Needs wmname installed
bspc config wmname LG3D

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# start compton
compton -b --config ~/.config/bspwm/compton.conf

# set wallpaper (needs nitrogen installed)
nitrogen --restore

## AUTOSTART Applications
#alttab -fg "#d58681" -bg "#4a4a4a" -frame "#eb564d" -t 128x150 -i 127x64 &
