[general]
separator = " "
default_icon = ""

[options]
no_names = true
remove_duplicates = false

[icons]

"Brave-browser" = ""
"Chromium-browser" = ""
"Daedalus Mainnet" = ""
"Deluge-gtk" = ""
"Font-manager" = ""
"Genymotion Player" = ""
"Org.gnome.Nautilus" = ""
"Rocket.Chat" = ""
"Tagaini Jisho" = ""
"Timeshift-gtk" = ""
"Uget-gtk" = ""
"Xfce4-terminal" = ""
"libreoffice-calc" = ""
Alacritty = ""
Bitwarden = ""
Firefox = ""
Gnome-genius = ""
Mailspring = ""
Notebook = ""
Pamac-manager = ""
Pavucontrol = ""
Signal = ""
Slack = ""
Spotify = ""
Termite = ""
Thunderbird = ""
Vmware = ""
Wfica = ""
code-oss = ""
mpv = ""
okular = ""
zoom = ""
