[general]
separator = " "
default_icon = ""

[icons]
"Brave-browser" = ""
Bitwarden = ""
"Genymotion Player" = ""
"Org.gnome.Nautilus" = ""
"Rocket.Chat" = ""
"Tagaini Jisho" = ""
"libreoffice-calc" = ""
Alacritty = ""
Gnome-genius = ""
Mailspring = ""
Notebook = ""
Pamac-manager = ""
Signal = ""
Slack = ""
Termite = ""
Thunderbird = ""
Wfica = ""
code-oss = ""
firefox = ""
zoom = ""
okular = ""
Vmware = ""
"Uget-gtk" = ""
"Font-manager" = ""
Spotify = ""
"Timeshift-gtk" = ""

[options]
no_names = true
remove_duplicates = false
