#!/bin/bash
apt install \
meson \
libstartup-notification0-dev \
libxcb-xkb-dev \
libstartup-notification0-dev \
libxcb-xinerama0-dev \
libxcb-randr0-dev \
libxcb-shape0-dev \
libxcb-util-dev \
libxcb-cursor-dev \
libxcb-keysyms1-dev \
libxcb-icccm4-dev \
libxcb-xrm-dev \
libxkbcommon-dev \
libxkbcommon-x11-dev \
libyajl-dev \
libpcre3-dev \
libcairo2-dev \
librust-pangocairo-dev \
libev-dev
